/*

https://github.com/yamazaki3104/BirdsScript

Copyright (c) YAMAZAKI Satoshi. All rights reserved.

KAWASEMI INTERPRETER 1.0 for Javascript

*/
function kawasemi_interpreter(s){function H(){return{d:"[stack]",b:"list",a:[],c:"",e:!1,f:"null"}}function r(g){return g.f?{d:g.d,b:g.b,a:g.a,c:g.c,e:g.e,f:g.f}:{d:g.d,b:g.b,a:g.a,c:g.c,e:g.e}}function I(g){for(var a in g){var h=g[a];"list"===h.b?I(h.a):"[catch]"===h.d&&"func_no"===h.b&&"on_dtor"===h.c&&z(u[h.a])}}function B(D,a){for(;g.length>D;){var h=g.pop();if("[catch]"===h.d&&"[event]"===a.d&&h.c===a.c){if("func_no"===h.b){var n=a.a;if(n instanceof Array)for(var l in n){var t=r(n[l]);"."===t.c[0]&&(t.c="_"+t.c.substr(1,
t.c.length-1));g.push(t)}return z(u[h.a])}n={d:"[stack]",b:"list",a:[],c:"literal",e:!1,f:"catch"};h.g=n;n.a.push(h);return n}if("[catch]"===h.d&&"on_dtor"===h.c)return"func_no"===h.b?z(u[h.a]):{d:"[stack]",b:h.b,a:h.a,c:"literal",e:!1,f:"on_dtor"};"list"===h.b&&I(h.a)}return a}function z(D){function a(a){return{d:"[event]",b:"run-time error",a:a,h:t}}function h(a){if("list_no"===a.b){var b=g.length;a=z(u[a.a]);a=B(b,a);if("[event]"===a.d)return a;for(var d in a.a)"[stack]"===a.a[d].d&&"."!==a.a[d].c[0]&&
(a.a[d].c="."+a.a[d].c);return a}if("ident"!==a.b)return a;for(d=g.length-1;0<=d;d--)if("[stack]"===g[d].d&&g[d].c===a.a)return g[d];d=r(a);d.c="_";return{d:"[event]",b:"exception",c:"on_undefined",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"undefined symbol.: "+a.a},d]}}function n(b,d,e){var f=h(e);if("[event]"===f.d)return f;if("int"!==f.b)return a("variable type mismatch.: "+f.a+" "+f.b);e=!1;if("ident"!==d.b)e=d;else for(var k=g.length-1;0<=k;k--)if(g[k].c===d.a){e=g[k];break}if(!1!==
e){if(!0===e.e)return a("cannot be set to a read-only property.: "+e.c+"."+e.b);if("int"!==e.b)return a("variable type mismatch.: "+l(e));if("*="===b)return e.a*=f.a,r(e);if("/="===b){if(0===f.a)return b=r(e),b.c="_",d=r(f),d.c="_idx",{d:"[event]",b:"exception",c:"on_division_by_zero",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"division by zero.: "+s(e)+" /= 0"},b,d]};e.a=Math.floor(e.a/f.a);return r(e)}if("%="===b){if(0===f.a)return b=r(e),b.c="_",d=r(f),d.c="_idx",{d:"[event]",b:"exception",
c:"on_division_by_zero",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"division by zero.: "+s(e)+" %= 0"},b,d]};e.a%=f.a;return r(e)}if("+="===b)return e.a+=f.a,r(e);if("-="===b)return e.a-=f.a,r(e)}e=r(d);e.c="_";return{d:"[event]",b:"exception",c:"on_undefined",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"undefined symbol.: "+d.a},e]}}function l(a){if("int"===a.b||"str"===a.b||"bool"===a.b)return a.a;if("list"===a.b){var b="[ ",d;for(d in a.a){var e=a.a[d];"[stack]"===e.d&&"."===e.c[0]&&
(b+=l(h(e))+", ")}return b+"]"}return"func_no"===a.b?"{ }":a.b}function s(a){if("str"===a.b)return a.c+":'"+a.a+"'.str";if("int"===a.b||"bool"===a.b)return a.c+":"+a.a+"."+a.b;if("list"===a.b){var b=a.c+":[ ",d;for(d in a.a){var e=a.a[d];"[stack]"===e.d&&(b+=s(h(e))+", ")}b+="]";a.f&&(b+="."+a.f);return b}return"func_no"===a.b?(a.c?a.c:"literal")+":{ }":a.c+":"+a.a+"."+a.b}if(!D)return[];for(var q=[],C=0;C<D.length;C++){var d=D[C];if("ident"!==d.b||")"!==d.a)q.push(d);else{for(var b=[],f=q.length-
1;0<=f;--f){var k=q.pop();b.unshift(k);if("ident"===k.b&&"("===k.a[0])break}if(!(0>=b.length))if(d=b[0].a,"(scope"===d){var f=g.length,e=z(u[b[1].a]),k=B(f,e);if("[event]"===k.d)return k;"list"===k.b&&0<k.a.length?q.push(k.a[k.a.length-1]):q.push(k)}else if("(,"===d){if(2>b.length)return a("arg_size < 2 : "+d);if(2<b.length)return a("arg_size > 2 : "+d);f=h(b[1]);if("[event]"===f.d)return f;q.push(r(f))}else if("(;"===d)for(var m in b){if("0"!==m&&(f=h(b[m]),"[event]"===f.d))return f}else if("(at"===
d||"(."===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);f=h(b[1]);if("[event]"===f.d)return f;e=b[2];if("(at"===d&&(e=h(b[2]),"[event]"===e.d))return e;if("ident"===e.b||"int"===e.b||"str"===e.b){var p=("."===e.a[0]?"":".")+e.a,b=!1;if("(."===d&&".type"===p)b=f.b,"func_no"===b&&(b="func"),b={d:"[stack]",b:"str",a:b,c:"literal",e:!1},q.push(b);else if("(."===d&&".size"===p){b=f.b;if("list"!==b)return a("not list-object : "+f.c+"."+f.b);b={d:"[stack]",b:"int",
a:f.a.length,c:"literal",e:!1};q.push(b)}else"(."===d&&".detail"===p&&(b={d:"[stack]",b:"str",a:s(f),c:"literal",e:!1},q.push(b));if(!1===b&&"[stack]"===f.d&&"list"===f.b){if(!1===b)for(m in f.a){b=f.a[m];if(b.c===p){q.push(b);break}b=!1}if(!1===b){k="";for(m=g.length-1;0<=m;m--)if("[stack]"===g[m].d&&g[m].c===p){b=g[m];break}!1!==b&&"int"===b.b&&0<=b.a&&b.a<f.a.length&&q.push(f.a[b.a])}if(!1===b)for(m in f.a){b=f.a[m];if(".unmatch"===b.c){b=r(b);q.push(b);break}b=!1}}if(!1===b){for(m=g.length-1;0<=
m;m--)if("[stack]"===g[m].d&&"unmatch"===g[m].c){b=r(g[m]);break}if(!1!==b&&"func_no"===b.b)if(k=g.length,d=r(f),d.c="_",g.push(d),g.push({d:"[stack]",b:"str",c:"_idx",e:!1,a:e.a}),b=z(u[b.a]),k=B(k,b),"[event]"===b.d)if("return"===b.b&&0<b.a.length)q.push({d:"[stack]",b:"list",a:b.a,c:"literal",e:!1,f:p});else return b;else"[stack]"===b.d&&0<b.a.length?q.push(b):b=!1}if(!1===b)return q=r(f),q.c="_",{d:"[event]",b:"exception",c:"on_unmatch",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"unmatch index.: "+
f.c+p},q,{d:"[stack]",b:"str",c:"_idx",e:!1,a:e.a}]}}else if("list"===e.b&&"list"===f.b&&"list"===e.b){b={d:"[stack]",b:"list",a:[],c:"literal",e:!1,f:p};for(m in e.a){var d="."+e.a[m].a,k=!1,F;for(F in f.a){var w=f.a[F];if(d===w.c){k=r(w);k.c="."+b.a.length;b.a.push(k);k=!0;break}}if(!1===k)for(F in f.a)if(w=f.a[F],".unmatch"===w.c){w=r(w);b.a.push(w);break}}q.push(b)}}else if("(:"===d||"(::"===d||"(->>"===d||"(<<-"===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+
d);f=b[1].a;if("ident"!==b[1].b){if("int"!==b[1].b)return a("cannot define.: "+f);f=""+f}e=h(b[2]);if("[event]"===e.d)return e;e={d:"[stack]",b:e.b,a:e.a,c:f,e:"(::"!==d,f:e.f};"(->>"===d?e.d="[catch]":"(<<-"===d&&(e.d="[label]");g.push(e);q.push(e)}else if("(="===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);e=function(b,d){var e=h(d);if("[event]"===e.d)return e;if("ident"!==b.b){if(!0===b.e&&!0===b.g.e)return a("cannot be set to a read-only property.: "+
b.g.c+"."+b.g.b);b.a=e.a;b.b=e.b;return b}for(var f=!1,k=g.length-1;0<=k;k--)if(f=g[k],"[stack]"===f.d&&f.c===b.a){if(!0===f.e)return a("cannot be set to a read-only property.: "+f.c+"."+f.b);if(f.b!==e.b)return a("type mismatch.: "+f.c+"."+f.b+" != "+e.c+"."+e.b);f.a=e.a;f.b=e.b;e=r(f);e.c="literal";return e}f=r(b);f.c="_";return{d:"[event]",b:"exception",c:"on_undefined",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"undefined symbol.: "+b.a},f]}}(b[1],b[2]);if("[event]"===e.d)return e;q.push(e)}else if("(<<"===
d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);if("out_stream"===b[1].f&&""===b[1].a){f=h(b[2]);if("[event]"===f.d)return f;E+=l(f);q.push(b[1])}else if("ident"!==b[1].b)return a("syntax-error?: "+d+" "+s(b[1]));for(m=g.length-1;0<=m;m--)if(d=g[m],"[stack]"===d.d&&d.c===b[1].a){if(!0===d.e)return a("cannot be set to a read-only property.: "+d.c+"."+d.b);if("list"===d.b){f=h(b[2]);if("[event]"===f.d)return f;"literal"===f.c?d.a.push({d:f.d,b:f.b,a:f.a,c:"."+
d.a.length,e:f.e,g:d}):(k=r(f),"."!==k.c[0]&&(k.c="."+k.c),d.a.push(k))}else if("str"===d.b)d.a=""+d.a+h(b[2]).a;else if("int"===d.b){q.push({d:"[stack]",b:d.b,a:d.a<<h(b[2]).a,c:"literal",e:!0});break}q.push(b[1]);break}}else if("(<"===d||"(>"===d||"(<="===d||"(>="===d||"(=="===d||"(!="===d||"(&&"===d||"(||"===d||"(*"===d||"(/"===d||"(%"===d||"(+"===d||"(-"===d||"(&"===d||"(|"===d||"(^"===d||"(>>"===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);q.push(function(b,
d,e){d=h(d);if("[event]"===d.d)return d;e=h(e);if("[event]"===e.d)return e;if(d.b!==e.b)return{d:"[stack]",b:"bool",a:!1,c:"literal",e:!0};if("(>"===b)return{d:"[stack]",b:"bool",a:d.a>e.a,c:"literal",e:!0};if("(<"===b)return{d:"[stack]",b:"bool",a:d.a<e.a,c:"literal",e:!0};if("(>="===b)return{d:"[stack]",b:"bool",a:d.a>=e.a,c:"literal",e:!0};if("(<="===b)return{d:"[stack]",b:"bool",a:d.a<=e.a,c:"literal",e:!0};if("(=="===b)return{d:"[stack]",b:"bool",a:d.a===e.a,c:"literal",e:!0};if("(!="===b)return{d:"[stack]",
b:"bool",a:d.a!==e.a,c:"literal",e:!0};if("(&&"===b)return{d:"[stack]",b:"bool",a:d.a&&e.a,c:"literal",e:!0};if("(||"===b)return{d:"[stack]",b:"bool",a:d.a||e.a,c:"literal",e:!0};if("str"===d.b&&"str"===e.b&&1===d.a.length&&1===e.a.length){if("(+"===b)return{d:"[stack]",b:d.b,a:String.fromCharCode(d.a.charCodeAt(0)+e.a.charCodeAt(0)),c:"literal",e:!0};if("(-"===b)return{d:"[stack]",b:d.b,a:String.fromCharCode(d.a.charCodeAt(0)-e.a.charCodeAt(0)),c:"literal",e:!0}}return"(*"===b?{d:"[stack]",b:d.b,
a:d.a*e.a,c:"literal",e:!0}:"(/"===b?0===e.a?(b=r(d),b.c="_",e=r(e),e.c="_idx",{d:"[event]",b:"exception",c:"on_division_by_zero",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"division by zero.: "+s(d)+" / 0"},b,e]}):{d:"[stack]",b:d.b,a:Math.floor(d.a/e.a),c:"literal",e:!0}:"(%"===b?0===e.a?(b=r(d),b.c="_",e=r(e),e.c="_idx",{d:"[event]",b:"exception",c:"on_division_by_zero",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"_e",e:!1,a:"division by zero.: "+s(d)+" % 0"},b,e]}):{d:"[stack]",b:d.b,a:d.a%
e.a,c:"literal",e:!0}:"(+"===b?{d:"[stack]",b:d.b,a:d.a+e.a,c:"literal",e:!0}:"(-"===b?{d:"[stack]",b:d.b,a:d.a-e.a,c:"literal",e:!0}:"(&"===b?{d:"[stack]",b:d.b,a:d.a&e.a,c:"literal",e:!0}:"(|"===b?{d:"[stack]",b:d.b,a:d.a|e.a,c:"literal",e:!0}:"(^"===b?{d:"[stack]",b:d.b,a:d.a^e.a,c:"literal",e:!0}:"(>>"===b?{d:"[stack]",b:d.b,a:d.a>>e.a,c:"literal",e:!0}:a(b)}(d,b[1],b[2]))}else if("(??"===d){if(3>b.length)return a("arg_size < 3 : "+d);if(4<b.length)return a("arg_size > 4 : "+d);if("bool"!==b[1].b)return a("argument type is not bool.: "+
b[1].c+"."+b[1].b);if(!0===b[1].a){e=z(u[b[2].a]);if("[event]"===e.d)return e;for(var G in e.a)q.push(e.a[G])}else if(4===b.length){e=z(u[b[3].a]);if("[event]"===e.d)return e;for(G in e.a)q.push(e.a[G])}}else if("(loop"===d){if(2>b.length)return a("arg_size < 2 : "+d);if(2<b.length)return a("arg_size > 2 : "+d);var w=999,d=g.length,x={d:"[stack]",b:"list",a:[],c:"literal",e:!1,f:"loop"};g.push({d:"[stack]",b:"int",a:0,c:"idx",e:!0});for(var A=0;A<w;A++){g[d].a=A;k=g.length;e=z(u[b[1].a]);k=B(k,e);
if("[event]"===e.d&&"break"===e.b){for(m in e.a.a){var v=r(e.a.a[m]);"."===v.c[0]&&(v.g=x.a,v.c="."+x.a.length,x.a.push(v))}break}if("[event]"!==e.d||"continue"!==e.b){if("[event]"===e.d&&"[event]"!==k.d){e=k;break}if("[event]"===e.d)return e;for(m in k.a)v=r(k.a[m]),v.g=x.a,v.c="."+x.a.length,x.a.push(v)}}if(A>=w)return{d:"[event]",b:"exception",c:"on_loop_limit_over",h:""===t?"":t,a:[{d:"[stack]",b:"str",c:"e",e:!1,a:"loop limit over.: "+w}]};for(;g.length>d;)g.pop();q.push(x)}else if("(each"===
d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);f=h(b[1]);if("[event]"===f.d)return f;w=0;if("str"===f.b)w=f.a.length;else if("int"===f.b)w=f.a;else if("list"===f.b)w=f.a.length;else return a("each type error: "+f.b);d=g.length;x={d:"[stack]",b:"list",a:[],c:"literal",e:!1,f:"each"};g.push({d:"[stack]",b:f.b,a:0,c:"it",e:!0});g.push({d:"[stack]",b:"int",a:0,c:"idx",e:!0});e=H();for(A=0;A<w;A++){"str"===f.b?g[d].a=f.a.substr(A,1):"int"===f.b?g[d].a=A:"list"===
f.b&&(k=r(h(f.a[A])),k.c="it",g[d]=k);if("list"===f.b){if(k=h(f.a[A]).c,"literal"!==k)if("."!==k[0])continue;else e=k.substr(1,k.length-1),k=parseInt(e,10),isNaN(k)?(g[d+1].a=e,g[d+1].b="str"):(g[d+1].a=k,g[d+1].b="int")}else g[d+1].a=A;k=g.length;e=z(u[b[2].a]);k=B(k,e);if("[event]"===e.d&&"break"===e.b){for(m in e.a.a)v=r(e.a.a[m]),v.g=x.a,v.c="."+x.a.length,x.a.push(v);break}if("[event]"!==e.d||"continue"!==e.b){if("[event]"===e.d&&"[event]"!==k.d){e=k;break}if("[event]"===e.d)return e;for(m in k.a)v=
r(k.a[m]),v.g=x.a,v.c="."+x.a.length,x.a.push(v)}}for(;g.length>d;)g.pop();q.push(x)}else{if("(break"===d){if(2>b.length)return a("arg_size < 2 : "+d);if(2<b.length)return a("arg_size > 2 : "+d);v=h(b[1]);return"list_no"!==v.b&&"list"!==v.b?a("argument type is not list-object.: "+d):{d:"[event]",b:"break",a:v}}if("(continue"===d)return 1>b.length?a("arg_size < 1 : "+d):1<b.length?a("arg_size > 1 : "+d):{d:"[event]",b:"continue",a:H()};if("(throw"===d)return 3>b.length?a("arg_size < 3 : "+d):3<b.length?
a("arg_size > 3 : "+d):"ident"!==b[1].b?a("argument is not catch-name.: "+d):"list_no"!==b[2].b&&"list"!==b[2].b?a("argument type is not list-object.: "+d):{d:"[event]",b:"exception",c:b[1].a,a:h(b[2]).a};if("(until"===d)return 3>b.length?a("arg_size < 3 : "+d):3<b.length?a("arg_size > 3 : "+d):"ident"!==b[1].b?a("argument is not repeat-name.: "+d):"list_no"!==b[2].b&&"list"!==b[2].b?a("argument is not list-object.: "+d):{d:"[event]",b:"until",c:b[1].a,a:h(b[2]).a};if("(++"===d){if(2>b.length)return a("arg_size < 2 : "+
d);if(2<b.length)return a("arg_size > 2 : "+d);q.push(n("+=",b[1],{d:"[token]",b:"int",a:1}))}else if("(--"===d){if(2>b.length)return a("arg_size < 2 : "+d);if(2<b.length)return a("arg_size > 2 : "+d);q.push(n("-=",b[1],{d:"[token]",b:"int",a:1}))}else if("(+="===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);q.push(n("+=",b[1],b[2]))}else if("(-="===d){if(3<b.length)return a("arg_size > 3 : "+d);if(3>b.length)return a("arg_size < 3 : "+d);q.push(n("-=",
b[1],b[2]))}else if("(*="===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);q.push(n("*=",b[1],b[2]))}else if("(/="===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);q.push(n("/=",b[1],b[2]))}else if("(%="===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);q.push(n("%=",b[1],b[2]))}else if("(call"===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+
d);f=h(b[1]);if("[event]"===f.d)return f;d=g.length;if(3===b.length){e=z(u[b[2].a]);if("[event]"===e.d)return e;for(m=g.length-1;d-1<m;m--)g[m].c="_"+g[m].c}for(b=0;b<d;b++)k=g[b].c,"_"===k[0]&&(g[b].c="_."+k);if(f.g)for(e=f.g.a,m=e.length-1;0<=m;m--)"[stack]"===e[m].d&&g.push(e[m]);k=g.length;if("func_no"!==f.b)return a("not function.: "+f.c+"."+f.b);e=z(u[f.a]);if("[event]"===e.d)if("return"!==e.b){if(e=B(k,e),"[event]"===e.d)return e}else e={d:"[stack]",b:"list",a:e.a,c:"literal",e:!1,f:f.c};for(e.f=
f.c;k<g.length;)f=g.pop(),f.g=e,e.a.unshift(f);for(;d<g.length;)f=g.pop();for(b in g)k=g[b].c,"_"===k[0]&&"."===k[1]&&(g[b].c=k.substr(2,k.length-2));q.push(e)}else{if("(return"===d){if(2>b.length)return a("arg_size < 2 : "+d);if(2<b.length)return a("arg_size > 2 : "+d);e=h(b[1]);if("[event]"===e.d)return e;if("list"!==e.b)return a("argument type is not list-object.: "+d);var y=[];for(m in q)p=q[m],"[stack]"===p.d&&(p.c?"literal"===p.c?p.c="."+y.length:"."!==p.c[0]&&(p.c="."+p.c):p.c="."+y.length,
y.push(p));for(m in e.a)p=r(e.a[m]),e.a[m].c?"."!==p.c[0]&&(p.c="."+p.c):(p=r(h(p)),p.c="."+y.length),y.push(p);return{d:"[event]",b:"return",a:y}}if("(range"===d){if(3>b.length)return a("arg_size < 3 : "+d);if(3<b.length)return a("arg_size > 3 : "+d);f=h(b[1]);if("[event]"===f.d)return f;if("int"!==f.b)return a("argument type is not int : "+f.c+"."+f.b);b=h(b[2]);if("[event]"===b.d)return b;if("int"!==b.b)return a("argument type is not int : "+b.c+"."+b.b);e={d:"[stack]",b:"list",a:[],c:"literal",
e:!1,f:"range"};for(y=f.a;;)if(e.a.push({d:"[stack]",b:"int",a:y,c:"."+e.a.length,e:!1}),f.a<b.a){if(++y,y>b.a)break}else if(--y,y<b.a)break;q.push(e)}else if("(line"===d)t=b[1].a;else return a("unsupported token.: "+d)}}}}m={d:"[stack]",b:"list",a:[],c:"literal",e:!1,f:"noname"};if(0===q.length)return m;for(y in q){p=q[y];"ident"===p.b?p=h(p):"list_no"===p.b&&(p=h(p));if("[event]"===p.d)return p;p=r(p);"[stack]"===p.d&&("literal"===p.c&&(p.c=m.a.length),"."!==p.c[0]&&(p.c="."+p.c),p.g=m,m.a.push(p))}return m}
var u=[],g=[],C=[],E="",t="",J=function(g){for(var a="",h=0;h<g.length;h++)switch(g[h]){case "'":a+="s";break;case '"':a+="S";break;case "/":a+="b";break;case "-":a+="b";break;case ".":a+="b";break;case "\n":a+="e";break;default:a+=" "}for(var n="",l=" ",h=0;h<a.length;h++){switch(a[h]){case "s":"s"===l?l=" ":"S"!==l&&(l="s");break;case "S":"S"===l?l=" ":"s"!==l&&(l="S")}n=" "!==l?n+l:n+a[h]}a="";l=" ";for(h=0;h<n.length;h++){c=n[h];switch(l+c){case " b":case "eb":"//"===g.substr(h,2)&&(c="c"),"---"===
g.substr(h,3)&&(c="c"),"..."===g.substr(h,3)&&(c="c")}switch(c){case "c":l="c";break;case "e":l=" "}" "===l&&(a+=g[h])}return a}(s);(function(g){u=[];for(var a=[],h=0;h<g.length;h++)if("}:}"===g[h])for(var n=[],l;l=a.pop();)if("ident"===l.b&&"{"===l.a){l=u.length;u.push(n);a.push({d:"[token]",b:"func_no",a:l});break}else n.unshift(l);else if("]:]"===g[h])for(n=[];l=a.pop();)if("ident"===l.b&&"["===l.a){l=u.length;u.push(n);a.push({d:"[token]",b:"list_no",a:l});break}else n.unshift(l);else n=g[h],
"a:true"===n?n={d:"[stack]",b:"bool",a:!0,c:"literal",e:!0}:"a:false"===n?n={d:"[stack]",b:"bool",a:!1,c:"literal",e:!0}:(l=n.substr(0,2),n="0:"===l?{d:"[stack]",b:"int",a:parseInt(n.substr(2,n.length-2),10),c:"literal",e:!0}:"s:"===l?{d:"[stack]",b:"str",a:n.substr(3,n.length-2-2),c:"literal",e:!0}:{d:"[token]",b:"ident",a:n.substr(2,n.length-2)}),a.push(n);u.push(a)})(function(g){for(var a="",h=0;h<J.length;h++)switch(g[h]){case " ":a+=" ";break;case "!":a+="a";break;case '"':a+="S";break;case "#":a+=
"a";break;case "$":a+="a";break;case "%":a+="a";break;case "&":a+="a";break;case "'":a+="s";break;case "(":a+="a";break;case ")":a+=")";break;case "*":a+="a";break;case "+":a+="a";break;case ",":a+="a";break;case "-":a+="a";break;case ".":a+="a";break;case "/":a+="a";break;case "0":a+="0";break;case "1":a+="0";break;case "2":a+="0";break;case "3":a+="0";break;case "4":a+="0";break;case "5":a+="0";break;case "6":a+="0";break;case "7":a+="0";break;case "8":a+="0";break;case "9":a+="0";break;case ":":a+=
"a";break;case ";":a+="a";break;case "<":a+="a";break;case "=":a+="a";break;case ">":a+="a";break;case "?":a+="a";break;case "@":a+="a";break;case "A":a+="a";break;case "B":a+="a";break;case "C":a+="a";break;case "D":a+="a";break;case "E":a+="a";break;case "F":a+="a";break;case "G":a+="a";break;case "H":a+="a";break;case "I":a+="a";break;case "J":a+="a";break;case "K":a+="a";break;case "L":a+="a";break;case "M":a+="a";break;case "N":a+="a";break;case "O":a+="a";break;case "P":a+="a";break;case "Q":a+=
"a";break;case "R":a+="a";break;case "S":a+="a";break;case "T":a+="a";break;case "U":a+="a";break;case "V":a+="a";break;case "W":a+="a";break;case "X":a+="a";break;case "Y":a+="a";break;case "Z":a+="a";break;case "[":a+="[";break;case "\\":a+="a";break;case "]":a+="]";break;case "^":a+="a";break;case "_":a+="a";break;case "`":a+="a";break;case "a":a+="a";break;case "b":a+="a";break;case "c":a+="a";break;case "d":a+="a";break;case "e":a+="a";break;case "f":a+="a";break;case "g":a+="a";break;case "h":a+=
"a";break;case "i":a+="a";break;case "j":a+="a";break;case "k":a+="a";break;case "l":a+="a";break;case "m":a+="a";break;case "n":a+="a";break;case "o":a+="a";break;case "p":a+="a";break;case "q":a+="a";break;case "r":a+="a";break;case "s":a+="a";break;case "t":a+="a";break;case "u":a+="a";break;case "v":a+="a";break;case "w":a+="a";break;case "x":a+="a";break;case "y":a+="a";break;case "z":a+="a";break;case "{":a+="{";break;case "|":a+="a";break;case "}":a+="}";break;case "~":a+="a";break;default:a+=
" "}for(var n="",l=" ",h=0;h<a.length;h++){switch(a[h]){case "s":"s"===l?l=" ":"S"!==l&&(l="s");break;case "S":"S"===l?l=" ":"s"!==l&&(l="S")}" "===l&&0<h&&"a"===a[h-1]&&"0"===a[h]?l="a":"a"===l&&"a"!==a[h]&&"0"!==a[h]&&(l=" ");n=" "!==l?n+l:n+a[h]}for(var a="",l=n[0],r=[],h=0;h<n.length;h++)l===n[h]?a+=g[h]:(" "!==l&&r.push(l+":"+a),a=g[h],l=n[h]);" "!==l&&r.push(l+":"+a);return r}(J));s={d:"[stack]",b:"list",a:[],c:"@",e:!1,f:"system_root"};s.a.push({d:"[stack]",b:"list",a:"",c:".co",e:!1,f:"out_stream"});
g.push(s);s=z(u[u.length-1]);s=B(0,s);"[event]"===s.d&&C.push(""+s.b+": "+("exception"===s.b?0<s.a.length?s.c+" "+s.a[0].a:s.c:s.a)+(s.hasOwnProperty("debug_line")&&""!==s.h?"\n\tline:"+s.h:""));for(var K in C)E+="\n"+C[K];return E};