function on_kawasemi(H){function w(){return{c:"[stack]",b:"list",a:[],d:"null",e:!1}}function F(g){for(var a in g){var h=g[a];"list"===h.b?F(h.a):"func_no"===h.b&&"dtor"===h.d&&x(p[h.a])}}function A(D){for(var a=w();D<g.length;){var h=g.pop();"list"===h.b?F(h.a):"func_no"===h.b&&"dtor"===h.d?a=x(p[h.a]):"out"===h.d&&(a=h)}return a}function x(D){function a(a){y.push("syntax-error : "+a+(""===s?"":"\n\tline:"+s));return{c:"[event]",b:"error",a:"syntax-error : "+a,f:"top"}}function h(a){y.push("exception : "+a+
(""===s?"":"\n\tline:"+s));return{c:"[event]",b:"exception",a:"exception : "+a,f:"top"}}function l(a){if("list_no"===a.b){var b=g.length;a=x(p[a.a]);if("[event]"===a.c)return a;for(;b<g.length;)g.pop();var b={c:"[stack]",b:"map",a:[],d:"literal",e:!1},d;for(d in a){var e=a[d];"[stack]"===e.c&&"literal"===e.d&&(e.d=""+d,e.h=b,b.b="list")}b.a=a;return b}if("ident"!==a.b)return a;d=a.a;for(a=g.length-1;0<=a;a--)if("[stack]"===g[a].c&&g[a].d===d)return g[a];y.push("undefined variable.: "+d+(""===s?"":
"\n\tline:"+s));return{c:"[event]",b:"error",a:"undefined-var : "+d,f:"top"}}function k(b,d){var e=l(d);if("[event]"===e.c)return e;if("ident"!==b.b){if(!0===b.e&&!0===b.h.e)return a("cannot be set to a constant.: "+b.a);b.a=e.a;b.b=e.b;return b}for(var f=g.length-1;0<=f;f--){var h=g[f];if("[stack]"===h.c&&h.d===b.a){if(!0===h.e)return a("cannot be set to a constant.: "+h.a);h.a=e.a;h.b=e.b;e=z(h);e.d="literal";return e}}y.push("undefined variable.: "+b.a+(""===s?"":"\n\tline:"+s));return{c:"[event]",
b:"error",a:"undefined-var : "+b.a,f:"top"}}function I(b,d,e){d=l(d);if("[event]"===d.c)return d;e=l(e);if("[event]"===e.c)return e;if(d.b!==e.b)return{c:"[stack]",b:"bool",a:!1,d:"literal",e:!0};if("(>"===b)return{c:"[stack]",b:"bool",a:d.a>e.a,d:"literal",e:!0};if("(<"===b)return{c:"[stack]",b:"bool",a:d.a<e.a,d:"literal",e:!0};if("(>="===b)return{c:"[stack]",b:"bool",a:d.a>=e.a,d:"literal",e:!0};if("(<="===b)return{c:"[stack]",b:"bool",a:d.a<=e.a,d:"literal",e:!0};if("(=="===b)return{c:"[stack]",
b:"bool",a:d.a===e.a,d:"literal",e:!0};if("(!="===b)return{c:"[stack]",b:"bool",a:d.a!==e.a,d:"literal",e:!0};if("(&&"===b)return{c:"[stack]",b:"bool",a:d.a&&e.a,d:"literal",e:!0};if("(||"===b)return{c:"[stack]",b:"bool",a:d.a||e.a,d:"literal",e:!0};if("str"===d.b&&"str"===e.b&&1===d.a.length&&1===e.a.length){if("(+"===b)return{c:"[stack]",b:d.b,a:String.fromCharCode(d.a.charCodeAt(0)+e.a.charCodeAt(0)),d:"literal",e:!0};if("(-"===b)return{c:"[stack]",b:d.b,a:String.fromCharCode(d.a.charCodeAt(0)-
e.a.charCodeAt(0)),d:"literal",e:!0}}return"(*"===b?{c:"[stack]",b:d.b,a:d.a*e.a,d:"literal",e:!0}:"(/"===b?{c:"[stack]",b:d.b,a:Math.floor(d.a/e.a),d:"literal",e:!0}:"(+"===b?{c:"[stack]",b:d.b,a:d.a+e.a,d:"literal",e:!0}:"(-"===b?{c:"[stack]",b:d.b,a:d.a-e.a,d:"literal",e:!0}:"(&"===b?{c:"[stack]",b:d.b,a:d.a&e.a,d:"literal",e:!0}:"(|"===b?{c:"[stack]",b:d.b,a:d.a|e.a,d:"literal",e:!0}:"(^"===b?{c:"[stack]",b:d.b,a:d.a^e.a,d:"literal",e:!0}:"(>>"===b?{c:"[stack]",b:d.b,a:d.a>>e.a,d:"literal",e:!0}:
a(b)}function B(b,d,e){e=l(e);if("[event]"===e.c)return e;if("int"!==e.b)return a("variable type mismatch.: "+e.a+" "+e.b);if("ident"!==d.b){if(!0===d.e)return a("cannot be set to a constant.: "+d.a);if("int"!==d.b)return a("variable type mismatch.:"+d.a);if("*="===b)return{c:"[stack]",b:"int",a:d.a*=e.a,d:"literal",e:!1};if("/="===b)return{c:"[stack]",b:"int",a:d.a=Math.floor(d.a/e.a),d:"literal",e:!1};if("+="===b)return{c:"[stack]",b:"int",a:d.a+=e.a,d:"literal",e:!1};if("-="===b)return{c:"[stack]",
b:"int",a:d.a-=e.a,d:"literal",e:!1};y.push("undefined variable.: "+d.a+" "+b+(""===s?"":"\n\tline:"+s));return{c:"[event]",b:"error",a:"undefined-var:"+d.a,f:"top"}}for(var f=d.a,h=g.length-1;0<=h;h--){var k=g[h];if(k.d===f){if(!0===k.e)return a("cannot be set to a constant.: "+k.a);if("int"!==k.b)return a("variable type mismatch.:"+k.a);if("*="===b)return{c:"[stack]",b:"int",a:k.a*=e.a,d:"literal",e:!1};if("/="===b)return{c:"[stack]",b:"int",a:k.a/=e.a,d:"literal",e:!1};if("+="===b)return{c:"[stack]",
b:"int",a:k.a+=e.a,d:"literal",e:!1};if("-="===b)return{c:"[stack]",b:"int",a:k.a-=e.a,d:"literal",e:!1}}}y.push("undefined variable.: "+d.a+" "+b+(""===s?"":"\n\tline:"+s));return{c:"[event]",b:"error",a:"undefined-var:"+d.a,f:"top"}}function z(a){return{c:a.c,b:a.b,a:a.a,d:a.d,e:a.e}}if(!D)return[];for(var m=[],E=0;E<D.length;E++){var f=D[E];if("ident"!==f.b||")"!==f.a){if("("===f.a||"(each"===f.a||"(loop"===f.a)f.g=g.length;m.push(f)}else{for(var e=[],d=m.length-1;0<=d;--d){var b=m.pop();e.unshift(b);
if("ident"===b.b&&"("===b.a[0])break}if(!(0>=e.length))if(f=e[0].a,"("===f)if(2>e.length)m.push(w());else{d=A(e[0].g);if("[event]"===d.c)return d;"null"===d.d?m.push(e[e.length-1]):m.push(d)}else if("(at"===f||"(."===f){if(3>e.length)return a("arg_size < 3 : "+f);if("@"===e[1].a)b=z(e[1]),b.a=e[1].a+e[2].a,b.b="int",m.push(b);else{d=l(e[1]);if("[event]"===d.c)return d;b=!1;if("[stack]"===d.c&&("list"===d.b||"map"===d.b)){var t=e[2];"(at"===f&&(t=l(e[2]));if(("list"===d.b||"map"===d.b)&&"int"===t.b&&
0<=t.a&&t.a<d.a.length)m.push(d.a[t.a]),b=!0;else{e=t.a;"map"===d.b&&(e=""+e);for(var n in d.a){b=d.a[n];if(b.d===e){m.push(b);break}b=!1}if(!1===b){var r="";for(n=g.length-1;0<=n;n--)if("[stack]"===g[n].c&&g[n].d===e){b=g[n];break}!1!==b&&"int"===b.b&&0<=b.a&&b.a<d.a.length&&m.push(d.a[b.a])}}if(!1===b)for(n in d.a){b=d.a[n];if("unmatch"===b.d){m.push(b);break}b=!1}}if(!1===b)return y.push("undefined variable.: "+t.a+(""===s?"":"\n\tline:"+s)),{c:"[event]",b:"error",a:"undefined-var : "+t.a,f:"top"}}}else if("(:"===
f||"(::"===f){if(3>e.length)return a("arg_size < 3 : "+f);d=e[1].a;if("ident"!==e[1].b){if("int"!==e[1].b)return a("cannot define.: "+d);d=""+d}t=l(e[2]);if("[event]"===t.c)return t;b={c:"[stack]",b:t.b,a:t.a,d:d,e:"(:"===f};g.push(b);m.push(b)}else if("(="===f){if(3>e.length)return a("arg_size < 3 : "+f);b=k(e[1],e[2]);if("[event]"===b.c)return b;m.push(b)}else if("(<<"===f){if(3>e.length)return a("arg_size < 3 : "+f);if("@.co"===e[1].a){b=l(e[2]);if("str"===b.b||"int"===b.b)v+=b.a;else if("list"===
b.b||"map"===b.b){v+="[ ";for(n in b.a)"."===b.a[n].d[0]&&(v+=b.a[n].d+":"+b.a[n].a+", ");v+="]"}m.push(e[1])}else if("ident"!==e[1].b)return a("syntax-error?: "+e[1].a);for(n=g.length-1;0<=n;n--)if(d=g[n],"[stack]"===d.c&&d.d===e[1].a){if(!0===d.e)return a("cannot be set to a constant.: "+e[1].a);if("map"===d.b||"list"===d.b)b=l(e[2]),"literal"===b.d?d.a.push({c:b.c,b:b.b,a:b.a,d:"."+d.a.length,e:b.e,h:d}):(b=z(b),d.a.push(b));else if("str"===d.b)d.a=""+d.a+l(e[2]).a;else if("int"===d.b){m.push({c:"[stack]",
b:d.b,a:d.a<<l(e[2]).a,d:"literal",e:!0});break}m.push(e[1]);break}}else if("(<"===f||"(>"===f||"(<="===f||"(>="===f||"(=="===f||"(!="===f||"(&&"===f||"(||"===f||"(*"===f||"(/"===f||"(+"===f||"(-"===f||"(&"===f||"(|"===f||"(^"===f||"(>>"===f){if(3>e.length)return a("arg_size < 3 : "+f);m.push(I(f,e[1],e[2]))}else if("(??"===f){if(3>e.length)return a("arg_size < 3 : "+f);if("bool"===e[1].b&&!0===e[1].a){b=x(p[e[2].a]);if("[event]"===b.c)return b;for(var C in b)m.push(b[C])}else if(4===e.length){b=
x(p[e[3].a]);if("[event]"===b.c)return b;for(C in b)m.push(b[C])}else m.push({c:"[token]",b:"bool",a:!1,e:!0})}else if("(loop"===f){if(3>e.length)return a("arg_size < 3 : "+f);g.push({c:"[stack]",b:"str",a:"",d:"out",e:!1});f=g.length;b=w();for(d=0;100>d;d++){b=x(p[e[2].a]);if("[event]"===b.c&&"break"===b.b){if(b.f!==e[1].a){d=A(e[0].g);if("[event]"===d.c)return d;m.push(w());return b}g.pop();b.a.d="out";g.push(b.a);break}if("[event]"===b.c&&"continue"===b.b){if(b.f!==e[1].a){d=A(e[0].g);if("[event]"===
d.c)return d;m.push(w());return b}}else if("[event]"===b.c)return b}if(100<=d)return h("loop limit-over: "+e[1].a);d=A(e[0].g);if("[event]"===d.c)return d;m.push(d)}else if("(each"===f){if(3>e.length)return a("arg_size < 3 : "+f);d=l(e[1]);if("[event]"===d.c)return d;r=0;if("str"===d.b)r=d.a.length;else if("int"===d.b)r=d.a;else if("map"===d.b)r=d.a.length;else if("list"===d.b)r=d.a.length;else return a("each type error: "+d.b);f=g.length;g.push({c:"[stack]",b:d.b,a:0,d:"it",e:!0});g.push({c:"[stack]",
b:"int",a:r,d:"max",e:!0});g.push({c:"[stack]",b:"str",a:"",d:"out",e:!1});for(var b=w(),u=0;u<r;u++){"str"===d.b?g[f].a=d.a.substr(u,1):"int"===d.b?g[f].a=u:"map"===d.b?(b=z(d.a[u]),b.d="it",g[f]=b):"list"===d.b&&(b=z(d.a[u]),b.d="it",g[f]=b);b=x(p[e[2].a]);if("[event]"===b.c&&"break"===b.b){if("noname"!==b.f){d=A(e[0].g);if("[event]"===d.c)return d;m.push(w());return b}g.pop();b.a.d="out";g.push(b.a);break}if("[event]"===b.c&&"continue"===b.b){if("noname"!==b.f){d=A(e[0].g);if("[event]"===d.c)return d;
m.push(w());return b}}else if("[event]"===b.c)return b}d=A(e[0].g);if("[event]"===d.c)return d;m.push(d)}else{if("(break"===f)return 2===e.length?{c:"[event]",b:"break",a:w(),f:e[1].a}:3>e.length?a("arg_size < 3 : "+f):{c:"[event]",b:"break",a:l(e[2]),f:e[1].a};if("(continue"===f)return 2>e.length?a("arg_size < 2 : "+f):{c:"[event]",b:"continue",a:w(),f:e[1].a};if("(++"===f){if(2>e.length)return a("arg_size < 2 : "+f);m.push(B("+=",e[1],{c:"[token]",b:"int",a:1}))}else if("(--"===f){if(2>e.length)return a("arg_size < 2 : "+
f);m.push(B("-=",e[1],{c:"[token]",b:"int",a:1}))}else if("(+="===f){if(3>e.length)return a("arg_size < 3 : "+f);m.push(B("+=",e[1],e[2]))}else if("(-="===f){if(3>e.length)return a("arg_size < 3 : "+f);m.push(B("-=",e[1],e[2]))}else if("(*="===f){if(3>e.length)return a("arg_size < 3 : "+f);m.push(B("*=",e[1],e[2]))}else if("(/="===f){if(3>e.length)return a("arg_size < 3 : "+f);m.push(B("/=",e[1],e[2]))}else if("(call"===f){if(3>e.length)return a("arg_size < 3 : "+f);d=l(e[1]);if("[event]"===d.c)return d;
if(d.h)for(b=d.h.a,n=b.length-1;0<=n;n--)"[stack]"===b[n].c&&g.push(b[n]);f=g.length;if(3===e.length){b=x(p[e[2].a]);if("[event]"===b.c)return b;for(n=g.length-1;f-1<n;n--)g[n].d="_"+g[n].d;g.push({c:"[stack]",b:"int",a:g.length-f,d:"arg_size",e:!0})}for(e=0;e<f;e++)r=g[e].d,"_"===r[0]&&(g[e].d="_."+r);r=g.length;if("func_no"!==d.b)return a("func_no: "+d.a);b=x(p[d.a]);if("[event]"===b.c){if("return"!==b.b){for(;f<g.length;)g.pop();return b}b=b.a}if("list"!==b.b&&"map"!==b.b){u={c:"[stack]",b:"list",
a:[],d:"out",e:!1};d=!1;for(n in b){var q=z(b[n]);q.d&&".literal"!==q.d&&"literal"!==q.d?"out"===q.d?d=q:(q.h=u,u.a.push(q)):!1===d&&(d=l(q))}!1!==d&&(d.d=".0",d.e=!0,d.h=u,u.a.push(d));b=u}else for(n in b.a)q=b.a[n],q.d="."+q.d;for(;r<g.length;)d=g.pop();for(;f<g.length;)d=g.pop(),d.h=b,b.a.push(d);for(e in g)r=g[e].d,"_"===r[0]&&"."===r[1]&&(g[e].d=r.substr(2,r.length-2));m.push(b)}else{if("(return"===f){if(2>e.length)return a("arg_size < 2 : "+f);b=l(e[1]);if("[event]"===b.c)return b;if("list"===
b.b||"map"===b.b)for(n in C=0,b.a)q=z(b.a[n]),b.a[n].d?q.d="."+q.d:(q=z(l(q)),q.d="."+C,C++),m.push(q);else return a("return not list : "+f);return{c:"[event]",b:"return",a:m}}if("(line"===f)s=e[1].a;else return a("program_error: "+f)}}}}return m}var p=[],g=[],y=[],v="",s="",G=function(g){for(var a="",h=0;h<g.length;h++)switch(g[h]){case "'":a+="s";break;case '"':a+="S";break;case "/":a+="b";break;case "-":a+="b";break;case ".":a+="b";break;case "\n":a+="e";break;default:a+=" "}for(var l="",k=" ",
h=0;h<a.length;h++){switch(a[h]){case "s":"s"===k?k=" ":"S"!==k&&(k="s");break;case "S":"S"===k?k=" ":"s"!==k&&(k="S")}l=" "!==k?l+k:l+a[h]}a="";k=" ";for(h=0;h<l.length;h++){c=l[h];switch(k+c){case " b":case "eb":"//"===g.substr(h,2)&&(c="c"),"---"===g.substr(h,3)&&(c="c"),"..."===g.substr(h,3)&&(c="c")}switch(c){case "c":k="c";break;case "e":k=" "}" "===k&&(a+=g[h])}return a}(H);(function(g){p=[];for(var a=[],h=0;h<g.length;h++)if("}:}"===g[h])for(var l=[],k;k=a.pop();)if("ident"===k.b&&"{"===k.a){k=
p.length;p.push(l);a.push({c:"[token]",b:"func_no",a:k});break}else l.unshift(k);else if("]:]"===g[h])for(l=[];k=a.pop();)if("ident"===k.b&&"["===k.a){k=p.length;p.push(l);a.push({c:"[token]",b:"list_no",a:k});break}else l.unshift(k);else l=g[h],"a:true"===l?l={c:"[stack]",b:"bool",a:!0,d:"literal",e:!0}:"a:false"===l?l={c:"[stack]",b:"bool",a:!1,d:"literal",e:!0}:(k=l.substr(0,2),l="0:"===k?{c:"[stack]",b:"int",a:parseInt(l.substr(2,l.length-2)),d:"literal",e:!0}:"s:"===k?{c:"[stack]",b:"str",a:l.substr(3,
l.length-2-2),d:"literal",e:!0}:{c:"[token]",b:"ident",a:l.substr(2,l.length-2)}),a.push(l);p.push(a)})(function(g){for(var a="",h=0;h<G.length;h++)switch(g[h]){case " ":a+=" ";break;case "!":a+="a";break;case '"':a+="S";break;case "#":a+="a";break;case "$":a+="a";break;case "%":a+="a";break;case "&":a+="a";break;case "'":a+="s";break;case "(":a+="a";break;case ")":a+=")";break;case "*":a+="a";break;case "+":a+="a";break;case ",":a+="a";break;case "-":a+="a";break;case ".":a+="a";break;case "/":a+=
"a";break;case "0":a+="0";break;case "1":a+="0";break;case "2":a+="0";break;case "3":a+="0";break;case "4":a+="0";break;case "5":a+="0";break;case "6":a+="0";break;case "7":a+="0";break;case "8":a+="0";break;case "9":a+="0";break;case ":":a+="a";break;case ";":a+="a";break;case "<":a+="a";break;case "=":a+="a";break;case ">":a+="a";break;case "?":a+="a";break;case "@":a+="a";break;case "A":a+="a";break;case "B":a+="a";break;case "C":a+="a";break;case "D":a+="a";break;case "E":a+="a";break;case "F":a+=
"a";break;case "G":a+="a";break;case "H":a+="a";break;case "I":a+="a";break;case "J":a+="a";break;case "K":a+="a";break;case "L":a+="a";break;case "M":a+="a";break;case "N":a+="a";break;case "O":a+="a";break;case "P":a+="a";break;case "Q":a+="a";break;case "R":a+="a";break;case "S":a+="a";break;case "T":a+="a";break;case "U":a+="a";break;case "V":a+="a";break;case "W":a+="a";break;case "X":a+="a";break;case "Y":a+="a";break;case "Z":a+="a";break;case "[":a+="[";break;case "\\":a+="a";break;case "]":a+=
"]";break;case "^":a+="a";break;case "_":a+="a";break;case "`":a+="a";break;case "a":a+="a";break;case "b":a+="a";break;case "c":a+="a";break;case "d":a+="a";break;case "e":a+="a";break;case "f":a+="a";break;case "g":a+="a";break;case "h":a+="a";break;case "i":a+="a";break;case "j":a+="a";break;case "k":a+="a";break;case "l":a+="a";break;case "m":a+="a";break;case "n":a+="a";break;case "o":a+="a";break;case "p":a+="a";break;case "q":a+="a";break;case "r":a+="a";break;case "s":a+="a";break;case "t":a+=
"a";break;case "u":a+="a";break;case "v":a+="a";break;case "w":a+="a";break;case "x":a+="a";break;case "y":a+="a";break;case "z":a+="a";break;case "{":a+="{";break;case "|":a+="a";break;case "}":a+="}";break;case "~":a+="a";break;default:a+=" "}for(var l="",k=" ",h=0;h<a.length;h++){switch(a[h]){case "s":"s"===k?k=" ":"S"!==k&&(k="s");break;case "S":"S"===k?k=" ":"s"!==k&&(k="S")}" "===k&&0<h&&"a"===a[h-1]&&"0"===a[h]?k="a":"a"===k&&"a"!==a[h]&&"0"!==a[h]&&(k=" ");l=" "!==k?l+k:l+a[h]}for(var a="",
k=l[0],p=[],h=0;h<l.length;h++)k===l[h]?a+=g[h]:(" "!==k&&p.push(k+":"+a),a=g[h],k=l[h]);" "!==k&&p.push(k+":"+a);return p}(G));x(p[p.length-1]);0<y.length&&(v+=y+"\n");return v};